apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: argo-cmp-timoni
spec:
  version: v0.1.1
  init:
    command: []
    args: []
  generate:
    command: ["/bin/sh", "-c"]
    args:
      - |
        /usr/local/bin/timoni build ${PARAM_APP_NAME} -n ${PARAM_NAMESPACE} . -f ${PARAM_VALUES_FILENAME}.yaml
  discover:
    filename: "values-*.yaml"
  parameters:
    static:
      - name: app-name
        title: "Timoni App Name"
        description: "Timoni App Name to build YAMLs"
        required: true
        strings: test-app
      - name: app-namespace
        title: "App Namespace"
        description: "App Namespace to give into YAMLs"
        required: true
        strings: timoni
      - name: values-filename
        title: "Timoni Values"
        description: "Values file to provide"
        tooltip: "Trim .yaml"
        required: true
        strings: values