apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: argo-cmp-timoni
spec:
  version: v0.1.0
  init:
    command: []
    args: []
  generate:
    command: ["/bin/sh", "-c"]
    args:
      - |
        /usr/local/bin/timoni build ${ARGOCD_ENV_APP_NAME} . -f ${ARGOCD_ENV_VALUES_FILENAME}.yaml
  preserveFileMode: false